import type React from "react"
import {
  Presentation,
  Users,
  Cpu,
  BrainCircuit,
  TrendingUp,
  Briefcase,
  Lightbulb,
  Wrench,
  GraduationCap,
  BookOpen,
  UsersRound,
  Handshake,
  InfinityIcon,
  Scale,
  ShieldCheck,
  Target,
  Zap,
  MessageSquare,
  Code2,
  Heart,
  Eye,
  CloudCog,
  Building,
  Network,
  DollarSign,
  Globe,
  CheckCircle,
  HelpCircle,
  User,
  FileText,
  Sparkles,
  Layers,
  Shuffle,
  BarChart3,
  Settings2,
  GitFork,
  Factory,
  Clock,
  AlertTriangle,
} from "lucide-react"

// Simplified Icon Map
export const IconMap = {
  Presentation,
  Users,
  Cpu,
  BrainCircuit,
  TrendingUp,
  Briefcase,
  Lightbulb,
  Wrench,
  GraduationCap,
  BookOpen,
  UsersRound,
  Handshake,
  InfinityIcon,
  Scale,
  ShieldCheck,
  Target,
  Zap,
  MessageSquare,
  Code2,
  Heart,
  Eye,
  CloudCog,
  Building,
  Network,
  DollarSign,
  Globe,
  CheckCircle,
  HelpCircle,
  User,
  FileText,
  Sparkles,
  Layers,
  Shuffle,
  BarChart3,
  Settings2,
  GitFork,
  Factory,
  Clock,
}

export interface Fragment {
  id: string // Unique ID for GSAP targeting & React key
  type:
    | "main-title"
    | "sub-title"
    | "presenter-names"
    | "date"
    | "slide-title"
    | "paragraph"
    | "bullet-point" // Can have sub-bullets or details
    | "highlight-text" // For key phrases or stats
    | "image-placeholder" // Will use visualQuery
    | "icon-heading" // Heading with an icon
    | "spacer"
    | "quote"
    | "definition-card"
  content: string | string[] // Main text content
  subContent?: string | string[] // Additional details for bullets or cards
  icon?: React.ElementType
  iconClass?: string
  accentColor?: string // e.g., 'text-sky-400'
  visualQuery?: string // For image placeholders or background hints
  layout?: "center" | "left" | "right" // Text alignment or basic layout hint
  fontSize?: "text-lg" | "text-xl" | "text-2xl" | "text-3xl" | "text-4xl" | "text-5xl"
  fontWeight?: "font-normal" | "font-medium" | "font-semibold" | "font-bold"
  fullWidth?: boolean
  columns?: number // For multi-column layouts of cards/items
  speakerNote?: string // Directly from the script
}

export interface SlideConfig {
  id: number
  slideTitleForDebug?: string // For easier identification during development
  fragments: Fragment[]
  backgroundVisualQuery: string // For the main slide background
  speaker: "Fahad" | "Sameer" | "Both"
  estimatedDuration: string
}

export const slides: SlideConfig[] = [
  // Slide 1: Title Slide
  {
    id: 1,
    slideTitleForDebug: "Title Slide",
    speaker: "Fahad",
    estimatedDuration: "1 min",
    backgroundVisualQuery: "abstract intertwined AI and human intelligence, futuristic, hopeful",
    fragments: [
      {
        id: "s1f1",
        type: "main-title",
        content: "The Impact of Agentic AI on Work Skills",
        fontSize: "text-5xl",
        fontWeight: "font-bold",
        layout: "center",
        speakerNote: "Good morning, everyone! Welcome...",
      },
      {
        id: "s1f2",
        type: "sub-title",
        content: "A Roadmap for Education and Retraining",
        fontSize: "text-3xl",
        layout: "center",
        accentColor: "text-sky-400",
      },
      { id: "s1f3", type: "spacer", content: "" },
      {
        id: "s1f4",
        type: "presenter-names",
        content: "Fahad Rashid & Sameer Abbas",
        fontSize: "text-2xl",
        layout: "center",
      },
      {
        id: "s1f5",
        type: "date",
        content: "June 2025",
        fontSize: "text-xl",
        layout: "center",
        accentColor: "text-slate-400",
      },
      {
        id: "s1f6",
        type: "paragraph",
        content:
          "Today, we're going to take you on a journey through one of the most transformative technological shifts of our time...",
        fontSize: "text-xl",
        layout: "center",
        speakerNote: "Today, we're going to take you on a journey...",
      },
      {
        id: "s1f7",
        type: "paragraph",
        content:
          "Over the next 15 minutes, we'll explore what Agentic AI means for the future workforce, identify critical skills, and present a comprehensive roadmap...",
        fontSize: "text-xl",
        layout: "center",
        speakerNote: "Over the next 15 minutes...",
      },
    ],
  },
  // Slide 2: Introduction - Agentic AI: Reshaping the Future of Work
  {
    id: 2,
    slideTitleForDebug: "Intro - Reshaping Future",
    speaker: "Sameer",
    estimatedDuration: "2 mins",
    backgroundVisualQuery: "dynamic abstract representation of AI transforming industries, data flows",
    fragments: [
      {
        id: "s2f1",
        type: "slide-title",
        content: "Agentic AI: Reshaping the Future of Work",
        speakerNote: "Thank you, Fahad. Let's start by understanding...",
      },
      {
        id: "s2f2",
        type: "paragraph",
        content: "Agentic AI: Autonomous decisions & complex task execution with minimal human oversight.",
        fontSize: "text-2xl",
        fontWeight: "font-medium",
        speakerNote: "Agentic AI is characterized by its ability...",
      },
      {
        id: "s2f3",
        type: "highlight-text",
        content: "Not just chatbots: Manages supply chains, personalized customer service, complex data analysis.",
        fontSize: "text-xl",
        accentColor: "text-purple-400",
        speakerNote: "We're not just talking about chatbots...",
      },
      { id: "s2f4", type: "spacer", content: "" },
      {
        id: "s2f5",
        type: "icon-heading",
        icon: TrendingUp,
        content: "The Numbers by 2030:",
        fontSize: "text-2xl",
        speakerNote: "But here's what makes this particularly urgent...",
      },
      {
        id: "s2f6",
        type: "bullet-point",
        icon: Users,
        iconClass: "text-red-400",
        content: "92 Million Jobs Displaced",
        fontSize: "text-xl",
      },
      {
        id: "s2f7",
        type: "bullet-point",
        icon: UsersRound,
        iconClass: "text-green-400",
        content: "170 Million New Roles Created",
        fontSize: "text-xl",
        speakerNote: "However, and this is crucial...",
      },
      {
        id: "s2f8",
        type: "paragraph",
        content: "This transformation is already underway. The question isn't IF, but ARE WE PREPARED?",
        fontSize: "text-xl",
        fontWeight: "font-semibold",
        accentColor: "text-amber-400",
        speakerNote: "The key insight here is that this transformation...",
      },
    ],
  },
  // Slide 3: What is Agentic AI?
  {
    id: 3,
    slideTitleForDebug: "What is Agentic AI?",
    speaker: "Fahad",
    estimatedDuration: "2 mins",
    backgroundVisualQuery: "evolution timeline from simple AI to complex neural networks, abstract brain",
    fragments: [
      {
        id: "s3f1",
        type: "slide-title",
        content: "What is Agentic AI?",
        speakerNote: "Now, let's dive deeper...",
      },
      {
        id: "s3f2",
        type: "highlight-text",
        content: "Evolution: From rule-based systems to sophisticated autonomous agents.",
        fontSize: "text-xl",
        speakerNote: "As you can see from this evolution timeline...",
      },
      { id: "s3f3", type: "icon-heading", icon: BrainCircuit, content: "Core Characteristics:", fontSize: "text-2xl" },
      {
        id: "s3f4",
        type: "definition-card",
        icon: Sparkles,
        content: "Autonomy",
        subContent: "Operate independently, making decisions without constant human intervention.",
        speakerNote: "First, autonomy...",
      },
      {
        id: "s3f5",
        type: "definition-card",
        icon: Target,
        content: "Goal-Driven Behavior",
        subContent: "Designed to achieve specific objectives and adapt strategies.",
        speakerNote: "Second, goal-driven behavior...",
      },
      {
        id: "s3f6",
        type: "definition-card",
        icon: Shuffle,
        content: "Adaptability",
        subContent: "Respond dynamically to changing environments and unexpected situations.",
        speakerNote: "Third, adaptability...",
      },
      {
        id: "s3f7",
        type: "highlight-text",
        content: "Foundation: LLMs, Machine Learning, Reinforcement Learning.",
        fontSize: "text-xl",
        accentColor: "text-emerald-400",
        speakerNote: "What sets Agentic AI apart...",
      },
      { id: "s3f8", type: "icon-heading", icon: Layers, content: "Real-World Applications:", fontSize: "text-2xl" },
      { id: "s3f9", type: "bullet-point", content: "Autonomous Virtual Assistants" },
      { id: "s3f10", type: "bullet-point", content: "Intelligent Business Process Management" },
      { id: "s3f11", type: "bullet-point", content: "Advanced Data Science & Insight Discovery" },
    ],
  },
  // Slide 4: Workforce Transformation
  {
    id: 4,
    slideTitleForDebug: "Workforce Transformation",
    speaker: "Sameer",
    estimatedDuration: "2 mins",
    backgroundVisualQuery: "human hand and robot hand connecting, collaborative future",
    fragments: [
      {
        id: "s4f1",
        type: "slide-title",
        content: "Workforce Transformation: A New Era of Collaboration",
        speakerNote: "This brings us to the heart of our discussion...",
      },
      {
        id: "s4f2",
        type: "icon-heading",
        icon: Settings2,
        content: "Automation of Routine & Sophisticated Tasks",
        fontSize: "text-xl",
        speakerNote: "First, we're seeing the automation...",
      },
      {
        id: "s4f3",
        type: "icon-heading",
        icon: Lightbulb,
        content: "Shift Towards Creative & Strategic Roles",
        fontSize: "text-xl",
        accentColor: "text-sky-400",
        speakerNote: "The most significant change...",
      },
      {
        id: "s4f4",
        type: "highlight-text",
        content: "Humans bring: Creativity, Emotional Intelligence, Ethical Reasoning.",
        fontSize: "text-xl",
        speakerNote: "While AI excels at processing...",
      },
      {
        id: "s4f5",
        type: "icon-heading",
        icon: AlertTriangle,
        content: "Challenges to Address:",
        fontSize: "text-2xl",
      },
      {
        id: "s4f6",
        type: "bullet-point",
        content: "Job Displacement Concerns (especially for women & low-income regions).",
        speakerNote: "But we must acknowledge the challenges...",
      },
      { id: "s4f7", type: "bullet-point", content: "Urgent Need for Comprehensive Reskilling Programs." },
      {
        id: "s4f8",
        type: "quote",
        content: "It's not humans VS AI – it's humans WITH AI.",
        fontSize: "text-2xl",
        fontWeight: "font-semibold",
        accentColor: "text-purple-400",
        speakerNote: "The key insight here is that successful adaptation...",
      },
    ],
  },
  // Slide 5: Essential Skills Part 1
  {
    id: 5,
    slideTitleForDebug: "Essential Skills Pt 1",
    speaker: "Fahad",
    estimatedDuration: "2.5 mins",
    backgroundVisualQuery: "stylized brain with interconnected skill icons, knowledge network",
    fragments: [
      {
        id: "s5f1",
        type: "slide-title",
        content: "Essential Skills Part 1: Navigating the AI Landscape",
        speakerNote: "So what are these essential skills...",
      },
      {
        id: "s5f2",
        type: "icon-heading",
        icon: Zap,
        content: "1. Prompt Engineering",
        fontSize: "text-3xl",
        accentColor: "text-amber-400",
        speakerNote: "First, and perhaps most surprisingly...",
      },
      {
        id: "s5f3",
        type: "paragraph",
        content: "The art & science of crafting precise inputs to guide AI outputs effectively.",
        fontSize: "text-xl",
      },
      {
        id: "s5f4",
        type: "highlight-text",
        content: "Up to 85% improvement in AI performance with effective prompting.",
        fontSize: "text-xl",
        fontWeight: "font-semibold",
        speakerNote: "Research shows that effective prompting...",
      },
      {
        id: "s5f5",
        type: "icon-heading",
        icon: BrainCircuit,
        content: "2. AI Literacy",
        fontSize: "text-3xl",
        accentColor: "text-emerald-400",
        speakerNote: "Second is AI literacy...",
      },
      {
        id: "s5f6",
        type: "paragraph",
        content:
          "Understanding AI capabilities, limitations, and ethical implications. Critical evaluation of AI results.",
        fontSize: "text-xl",
      },
      {
        id: "s5f7",
        type: "icon-heading",
        icon: Code2,
        content: "3. Technical Skills",
        fontSize: "text-3xl",
        accentColor: "text-rose-400",
        speakerNote: "Third are technical skills...",
      },
      {
        id: "s5f8",
        type: "paragraph",
        content: "Proficiency in ML, data science, software engineering. Foundational understanding of AI systems.",
        fontSize: "text-xl",
      },
      {
        id: "s5f9",
        type: "highlight-text",
        content: "Integration: Technical Knowledge + AI Literacy + Prompt Engineering = Meaningful Collaboration",
        fontSize: "text-xl",
        fontWeight: "font-semibold",
        accentColor: "text-sky-400",
        speakerNote: "The key insight here is that these skills work together...",
      },
    ],
  },
  // Slide 6: Essential Skills Part 2
  {
    id: 6,
    slideTitleForDebug: "Essential Skills Pt 2",
    speaker: "Sameer",
    estimatedDuration: "2 mins",
    backgroundVisualQuery: "human silhouette with glowing heart and brain, emphasizing human qualities",
    fragments: [
      {
        id: "s6f1",
        type: "slide-title",
        content: "Essential Skills Part 2: Beyond Technicalities",
        speakerNote: "Now let's explore the skills...",
      },
      {
        id: "s6f2",
        type: "icon-heading",
        icon: Heart,
        content: "4. Soft Skills (Uniquely Human)",
        fontSize: "text-3xl",
        accentColor: "text-rose-400",
      },
      {
        id: "s6f3",
        type: "bullet-point",
        icon: Lightbulb,
        content: "Creativity: Novel ideas, innovative problem-solving.",
      },
      { id: "s6f4", type: "bullet-point", icon: Eye, content: "Critical Thinking: Evaluate info, nuanced judgments." },
      {
        id: "s6f5",
        type: "bullet-point",
        icon: Users,
        content: "Emotional Intelligence: Empathy, relationship building.",
      },
      {
        id: "s6f6",
        type: "icon-heading",
        icon: BookOpen,
        content: "5. Domain Expertise",
        fontSize: "text-3xl",
        accentColor: "text-purple-400",
        speakerNote: "Domain expertise represents...",
      },
      {
        id: "s6f7",
        type: "bullet-point",
        icon: Briefcase,
        content: "Industry Knowledge: Real-world context and meaning.",
      },
      {
        id: "s6f8",
        type: "bullet-point",
        icon: ShieldCheck,
        content: "Regulatory Awareness: Legal and ethical compliance.",
      },
      { id: "s6f9", type: "bullet-point", icon: CloudCog, content: "Operational Context: Practical implementation." },
      {
        id: "s6f10",
        type: "highlight-text",
        content: "Irreplaceable: Human Connection, Complex Judgment, Ethical Reasoning.",
        fontSize: "text-xl",
        fontWeight: "font-semibold",
        speakerNote: "These skills remain irreplaceable...",
      },
    ],
  },
  // Slide 7: Education Roadmap
  {
    id: 7,
    slideTitleForDebug: "Education Roadmap",
    speaker: "Fahad",
    estimatedDuration: "2.5 mins",
    backgroundVisualQuery: "stylized roadmap with stages: K-12, Higher Ed, Professional Dev",
    fragments: [
      {
        id: "s7f1",
        type: "slide-title",
        content: "Education Roadmap: Building the Future Workforce",
        speakerNote: "Understanding the skills we need...",
      },
      {
        id: "s7f2",
        type: "icon-heading",
        icon: GraduationCap,
        content: "K-12 Education",
        fontSize: "text-2xl",
        accentColor: "text-green-400",
        speakerNote: "Starting with K-12 education...",
      },
      { id: "s7f3", type: "bullet-point", content: "Integrate AI literacy & digital skills early." },
      { id: "s7f4", type: "bullet-point", content: "Project-based learning for critical thinking." },
      {
        id: "s7f5",
        type: "icon-heading",
        icon: Building,
        content: "Higher Education",
        fontSize: "text-2xl",
        accentColor: "text-blue-400",
        speakerNote: "At the higher education level...",
      },
      { id: "s7f6", type: "bullet-point", content: "Specialized AI degrees & certificates." },
      { id: "s7f7", type: "bullet-point", content: "AI collaboration skills across all disciplines." },
      { id: "s7f8", type: "bullet-point", content: "Hands-on experience: AI labs, internships." },
      {
        id: "s7f9",
        type: "icon-heading",
        icon: Wrench,
        content: "Professional Development",
        fontSize: "text-2xl",
        accentColor: "text-yellow-400",
        speakerNote: "For working professionals...",
      },
      { id: "s7f10", type: "bullet-point", content: "Flexible, accessible training (e.g., prompt engineering)." },
      { id: "s7f11", type: "bullet-point", content: "Industry certifications to validate skills." },
      { id: "s7f12", type: "icon-heading", icon: CheckCircle, content: "Success Stories:", fontSize: "text-xl" },
      { id: "s7f13", type: "bullet-point", content: "PwC: 8.3M employees trained." },
      { id: "s7f14", type: "bullet-point", content: "Intel: AI Workforce Program with 110 community colleges." },
      { id: "s7f15", type: "bullet-point", content: "AWS: Skills to Jobs Tech Alliance." },
    ],
  },
  // Slide 8: Collaboration & Lifelong Learning
  {
    id: 8,
    slideTitleForDebug: "Collaboration & Lifelong Learning",
    speaker: "Sameer",
    estimatedDuration: "2 mins",
    backgroundVisualQuery: "infinity symbol intertwined with network connections, continuous learning",
    fragments: [
      {
        id: "s8f1",
        type: "slide-title",
        content: "Collaboration & Lifelong Learning",
        speakerNote: "Creating this educational infrastructure...",
      },
      {
        id: "s8f2",
        type: "icon-heading",
        icon: Handshake,
        content: "Industry Collaboration",
        fontSize: "text-2xl",
        accentColor: "text-sky-400",
        speakerNote: "Industry collaboration is essential...",
      },
      { id: "s8f3", type: "bullet-point", content: "Co-develop curricula with educational institutions." },
      { id: "s8f4", type: "bullet-point", content: "Offer apprenticeships for hands-on experience." },
      {
        id: "s8f5",
        type: "icon-heading",
        icon: InfinityIcon,
        content: "Lifelong Learning",
        fontSize: "text-2xl",
        accentColor: "text-purple-400",
        speakerNote: "The concept of lifelong learning...",
      },
      { id: "s8f6", type: "bullet-point", content: "Embrace continuous education & adaptability." },
      { id: "s8f7", type: "bullet-point", content: "Access to ongoing workshops, online courses." },
      {
        id: "s8f8",
        type: "icon-heading",
        icon: Globe,
        content: "Inclusive Access",
        fontSize: "text-2xl",
        accentColor: "text-emerald-400",
        speakerNote: "Perhaps most importantly...",
      },
      {
        id: "s8f9",
        type: "bullet-point",
        content: "Affordable training, targeted outreach to underrepresented groups.",
      },
      {
        id: "s8f10",
        type: "highlight-text",
        content: "Goals by 2030: Reduce skills gap by 85%, Retrain 50M+ workers.",
        fontSize: "text-xl",
        fontWeight: "font-semibold",
        speakerNote: "The statistics show our ambitious goals...",
      },
    ],
  },
  // Slide 9: Conclusion
  {
    id: 9,
    slideTitleForDebug: "Conclusion",
    speaker: "Fahad",
    estimatedDuration: "1.5 mins",
    backgroundVisualQuery: "balanced scale with AI on one side and human collaboration on the other, bright future",
    fragments: [
      {
        id: "s9f1",
        type: "slide-title",
        content: "Conclusion: Embracing the AI Future",
        speakerNote: "As we reach the conclusion...",
      },
      {
        id: "s9f2",
        type: "icon-heading",
        icon: Scale,
        content: "A Critical Juncture: Actively Shape the AI Transformation",
        fontSize: "text-2xl",
      },
      {
        id: "s9f3",
        type: "highlight-text",
        content: "Cultivate: Prompt Engineering, AI Literacy, Soft Skills.",
        fontSize: "text-xl",
        speakerNote: "The path forward requires us...",
      },
      {
        id: "s9f4",
        type: "highlight-text",
        content: "Strategy: Mitigate displacement, Promote inclusivity, Unlock AI's potential.",
        fontSize: "text-xl",
        accentColor: "text-sky-400",
      },
      { id: "s9f5", type: "icon-heading", icon: TrendingUp, content: "Expected Outcomes:", fontSize: "text-2xl" },
      { id: "s9f6", type: "bullet-point", content: "Enhanced Productivity" },
      { id: "s9f7", type: "bullet-point", content: "Accelerated Innovation" },
      { id: "s9f8", type: "bullet-point", content: "Workforce Resilience" },
      {
        id: "s9f9",
        type: "quote",
        content: "The time to act is NOW.",
        fontSize: "text-3xl",
        fontWeight: "font-bold",
        accentColor: "text-amber-400",
        speakerNote: "The time to act is now...",
      },
      {
        id: "s9f10",
        type: "paragraph",
        content: "Prepare workforce, Foster collaboration, Continuously innovate.",
        fontSize: "text-xl",
        speakerNote: "This requires three key actions...",
      },
    ],
  },
  // Slide 10: Thank You & Q&A
  {
    id: 10,
    slideTitleForDebug: "Q&A",
    speaker: "Both",
    estimatedDuration: "1 min",
    backgroundVisualQuery: "calm, professional background with subtle network or connection motif",
    fragments: [
      {
        id: "s10f1",
        type: "main-title",
        content: "Thank You",
        fontSize: "text-5xl",
        layout: "center",
        speakerNote: "Thank you for your attention...",
      },
      {
        id: "s10f2",
        type: "sub-title",
        content: "Questions & Discussion",
        fontSize: "text-3xl",
        layout: "center",
        accentColor: "text-sky-400",
      },
      { id: "s10f3", type: "spacer", content: "" },
      {
        id: "s10f4",
        type: "icon-heading",
        icon: User,
        content: "Fahad Rashid (F2022266416)",
        fontSize: "text-xl",
        layout: "center",
      },
      {
        id: "s10f5",
        type: "icon-heading",
        icon: User,
        content: "Sameer Abbas (F2022266420)",
        fontSize: "text-xl",
        layout: "center",
      },
      { id: "s10f6", type: "spacer", content: "" },
      {
        id: "s10f7",
        type: "paragraph",
        content:
          'Research Paper: "The Impact of Agentic AI on the Future of Work and Skill Requirements: A Roadmap for Education and Retraining" - June 2025',
        fontSize: "text-lg",
        layout: "center",
        accentColor: "text-slate-400",
        speakerNote: "Our research...",
      },
    ],
  },
]
